### ISSUE TITLE
版本不对

### ISSUE THREAD

**Issue by leo-yuan17** [myhloli/Magic-PDF#4]
### Description of the bug | 错误描述

pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com -i https://mirrors.aliyun.com/pypi/simple使用这个命令后，安装的版本是magic-pdf, version 0.6.1

### How to reproduce the bug | 如何复现

pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com -i https://mirrors.aliyun.com/pypi/simple使用这个命令后，安装的版本是magic-pdf, version 0.6.1

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
需要在conda创建的虚拟环境中安装，且确保自己的cpu是x86-64架构，以及python版本为3.10
